w3c/vc-data-model-2.0-test-suite

contexts.json
example-server.js
notes.md
tests/10-vcdm2.js
tests/input/credential-context-order-fail.json
tests/input/credential-context-order-ok.json
tests/input/credential-evidences-ok.json
tests/input/credential-redef-type-fail.json
tests/input/credential-redef-type2-fail.json
tests/input/credential-refresh-no-id-fail.json
tests/input/credential-refresh-no-type-fail.json
tests/input/credential-refresh-non-url-id-fail.json
tests/input/credential-refresh-ok.json
tests/input/credential-refreshs-ok.json
tests/input/credential-schema-no-id-fail.json
tests/input/credential-schema-no-type-fail.json
tests/input/credential-schema-non-url-id-fail.json
tests/input/credential-schema-ok.json
tests/input/credential-schemas-ok.json
tests/input/credential-termsofuse-id-ok.json
tests/input/credential-termsofuse-no-type-fail.json
tests/input/credential-termsofuses-ok.json

- Validate credentialSchema, refreshService, termsOfUse, and evidence.
- Handle term redefinition
- Implement credential-type-specific context order
- Document test suite special rules

Add more tests

---

.eslintrc.cjs
.github/workflows/main.yml
example-server.js
tests/10-vcdm2.js
tests/assertions.js
tests/mock.data.js
tests/receive-json.js

Lints the tests to pass the linter and removes unused variables and comments out unused functions.
I disabled the max-length rule in this project as concatenating all of those test files down is always an issue.

Lint files

---

example-server.js
tests/10-vcdm2.js
tests/input/credential-context-combo4-fail.json
tests/input/credential-issuer-nonurl-fail.json
tests/input/credential-not-url-id-fail.json
tests/input/credential-refresh-non-url-id-fail.json
tests/input/credential-schema-non-url-id-fail.json
tests/input/credential-status-nonurl-id-fail.json
tests/input/credential-type-mapped-nonurl-fail.json

https://github.com/digitalbazaar/vc-data-model-2-test-suite/issues/5
Addresses the issue where URNs were being used as invalid URLs.

Add invalid urls

---

tests/10-vcdm2.js

Removes not implemented from test and report.

Remove not implemented from tests and report.

---

package.json

Removes an uncaught instance of VCDM from the package.json in the test title.

Remove VCDM from package.json test command.

---

README.md

This PR updates the README with more accurate VC v2.0 compatible VCs.

Use more accurate examples in README.md.

---

README.md

This PR updates the README with context required and expanded information for the implementations.
This is a draft PR until all tests have been reviewed and we can finalize what endpoints and contexts are needed.

Use standard readme

---

README.md

Two minor changes to the README that should improve comprehension.

Correct typo readme

---

tests/10-vcdm2.js
tests/data-generator.js
tests/input/credential-nonsingle-id-fail.json
tests/input/credential-not-url-id-fail.json
tests/input/credential-single-id-ok.json

Cleans up tests data:
1. adds example context to test suites where needed
3. update documentLoader to support examples context.

Add examples context

---

tests/10-vcdm2.js

Refresh Services should probably be tested in their own suite.

Skip refreshService tests (these should be in a separate suite).

---

tests/10-vcdm2.js

looks like spaces were missing from a revised test title.

Space VC context test title.

---

tests/10-vcdm2.js

Simple PR that fixes indentation issues in the test descriptions.

Fix indentation issues.

---

localConfig.example.cjs

vpVerifier is required for this test, let's add it to the localconfig example

Add vpverifier to local config example

---

localConfig.example.cjs
tests/10-vcdm2.js
tests/TestEndpoints.js
tests/input/credential-issuer-no-url-fail.json
tests/input/credential-issuer-null-fail.json
tests/input/credential-issuer-object-id-no-url-fail.json
tests/input/credential-issuer-object-id-null-fail.json
tests/input/credential-issuer-object-ok.json
tests/input/names-and-descriptions/issuer-description-extra-prop-en-fail.json
tests/input/names-and-descriptions/issuer-description-language-direction-en-ok.json
tests/input/names-and-descriptions/issuer-description-language-en-ok.json
tests/input/names-and-descriptions/issuer-description-ok.json
tests/input/names-and-descriptions/issuer-description-optional-ok.json
tests/input/names-and-descriptions/issuer-multi-language-description-ok.json
tests/input/names-and-descriptions/issuer-multi-language-name-ok.json
tests/input/names-and-descriptions/issuer-name-extra-prop-en-fail.json
tests/input/names-and-descriptions/issuer-name-language-direction-en-ok.json
tests/input/names-and-descriptions/issuer-name-ok.json
tests/input/names-and-descriptions/issuer-name-optional-ok.json
tests/mock.data.js

Some of the work from #82 got lost during re-base, I'm re-introducing it here. This should have already been reviewed but please have a look!

Fix issuer tests

---

tests/10-vcdm2.js

Working my way through the full list of asserts/shoulds. The goal is to provide meaningful/actionable output to implementers.
Related to this PR improving error display: https://github.com/digitalbazaar/mocha-w3c-interop-reporter/pull/40
Would love early feedback if you can spare the cycles.

Add failure messages.

---

README.md

docs(fix): remove trailing comma in JSON

---

tests/10-vcdm2.js
tests/input/presentation-context-combo1-ok.json
tests/input/presentation-context-combo2-ok.json

- Fix parentheticals in subsequent items test.
- Move VP create and verify options to outer scope.
- Expand context tests for VPs.

Expand context tests

---

tests/10-vcdm2.js

Likely going to conflict with other pending PRs...

Add skip messages to pending tests.

---

tests/10-vcdm2.js
tests/TestEndpoints.js

- Remove inline checks option; use main config.
- Move challenge into endpoint functions.

Refactor inline options.

---

tests/10-vcdm2.js

- Reword credentialSubject tests.
- Update section numbers for Securing Mechanisms.

Update a handful of MUSTs.

---

tests/4-3-contexts.js
tests/4-4-identifiers.js
tests/4-5-types.js
tests/4-6-names-and-descriptions.js
tests/4-8-credential-subject.js
tests/4-9-validity-period.js
tests/410-status.js
tests/411-data-schemas.js
tests/412-securing-mechanisms.js
tests/413-verifiable-presentations.js

- Update section comments to match spec.
- Fix up quotes in Status section.
- Fix up quote in Data Schemas section.
- Fix up quote in Verifiable Presentations section.

Match spec text.

---

tests/1-3-conformance.js
tests/4-8-credential-subject.js
tests/4-9-validity-period.js
tests/413-verifiable-presentations.js
tests/50-advanced-concepts.js
tests/assertions.js

- Remove remaining TODO items from Conformance.
- Remove TODO about empty credentialSubject objects.
- Refactor shared temporality test into func.
- Move testTemporality to assertions.js.
- Remove ambiguous TODO.
- Update text for Extensibility test.

Clean up more TODOs.

---

tests/assertions.js

Remove another strict HTTPError check

---

tests/1.03-conformance.js

We have always skipped this one. It only confuses/concerns people.

Remove test covered by test suite.

---

tests/input/relatedResource/relatedResource-with-mediaType-ok.json

Make relatedResource IDs unique in mediaType test.
