- contexts.json
- tests/input/credential-id-other-ok.json
- tests/input/credential-not-url-id-fail.json
- tests/input/credential-single-id-ok.json
- tests/input/credential-subject-multiple-ok.json
Checks the following tests:
if present: "The id property MUST express an identifier that others are expected to use when expressing statements about a specific thing identified by that identifier." | ✓ | ✓ | ✓
if present: "The id property MUST NOT have more than one value." | ✓ | ✓ | ✓
if present: "The value of the id property MUST be a URL which MAY be dereferenced." | ❌ | ✓ | ✓
The value of the id property MUST be a single URL.
Some of these tests were failing because the term `description` was used in them and description is not found in the VC 2.0 context.
It also removes the custom context: `  "https://example.org/cool.json": {},`
> Check id tests

- tests/10-vcdm2.js
This is a safety precaution before this suite is publicly released.
Currently in mocha if a before statement fails the tests just aren't run.
In the case of this suite, that results in no implementations' tests running at all.
In order to avoid this, the before statement has been removed so that if an
implementation fails to issue a VC that implementation will fail the test the issuance
fails on. This creates a more accurate test record while also removing the frustration of not
being able to run the tests at all if a single implementer's issuer is down.
It does create 2 redundant calls on the issuer per implementation (up from one), but 
the stability is way more important IMHO if multiple implementers will be adding themselves to this suite.
> Remove before block issue & prove for stability.

- tests/input/credential-context-combo3-fail.json
- tests/input/credential-issuer-nonurl-fail.json
- tests/input/credential-not-url-id-fail.json
- tests/input/credential-refresh-non-url-id-fail.json
- tests/input/credential-schema-non-url-id-fail.json
- tests/input/credential-status-nonurl-id-fail.json
- tests/input/credential-type-mapped-nonurl-fail.json
Addresses:
https://github.com/digitalbazaar/vc-data-model-2-test-suite/issues/27
Bug: it turns out between the vocab in the Vc2.0 context and the somewhat liberal way json-ld creates relative urls, our existing `not-a-url` tests were not failing in the way they were intended. This PR updates those tests to use a full invalid url with the `https` protocol. Further issues will need to be made on `json-ld` processors as it looks like what `json-ld` will turn into a relative url is kind of interesting.
> Use an invalid url with https protocol for invalid url tests.

- .github/workflows/main.yml
- package.json
1. unpins test runner so it will run on the latest version of node 20
2. updates engines.node to >= 18 to match other test projects (semver.satisifies likes this pattern)
> Unpin node 20.8

- tests/10-vcdm2.js
Changes the narrow type test to a SHOULD
> Update language for narrow type test.

- CHANGELOG.md
- tests/10-vcdm2.js
- tests/input/credential-issuer-multi-language-name-ok.json
- tests/input/credential-issuer-name-extra-prop-en-fail.json
- tests/input/credential-issuer-name-language-direction-en-ok.json
- tests/input/credential-issuer-name-language-en-ok.json
- tests/input/credential-issuer-name-ok.json
Adds a test for "If present, the value of the issuer.name property MUST be a string or a language value object as described in 10.1 Language and Base Direction."
1. create an invalid "value object" with an extra prop like "url"
2. create a value object array with multiple languages
3. add a test with `@direction`
> Add issuer name tests.

- CHANGELOG.md
- tests/10-vcdm2.js
- tests/input/credential-issuer-description-extra-prop-en-fail.json
- tests/input/credential-issuer-description-language-direction-en-ok.json
- tests/input/credential-issuer-description-language-en-ok.json
- tests/input/credential-issuer-description-ok.json
- tests/input/credential-issuer-description-optional-ok.json
- tests/input/credential-issuer-multi-language-description-ok.json
- tests/input/credential-issuer-name-optional-ok.json
1. Add invalid language object
2. Add direction
3. Add array of language tags
> Add initial issuer.description tests.

- CHANGELOG.md
- tests/10-vcdm2.js
Just to simple renamings to match current spec text.
> Update statements for credentialStatus id & type + credentialSchema test

- README.md
- tests/10-vcdm2.js
- tests/TestEndpoints.js
- tests/data-generator.js
- tests/input/credential-single-id-ok.json
This is clean up: it removes tons of unneeded stuff from the actual test suite and instead creates an Endpoints class that really helps make the suite cleaner and makes it almost more inline with the rest of the suites. It also moves the challenge generation to `data-generator.js` further decluttering the test file.
> Use endpoints class

- respecConfig.json
This is to fulfil the VCDM CR Transition request comment https://github.com/w3c/transitions/issues/587#issuecomment-1900582168.
Cc: @plehegar @msporny
> Update respecConfig.json to use 'base' and not 'NOTE' as a spec status

- .eslintrc.cjs
- .reuse/dep5
- CHANGELOG.md
- LICENSE.md
- LICENSES/LicenseRef-w3c-3-clause-bsd-license-2008.md
- LICENSES/LicenseRef-w3c-test-suite-license-2023.md
- README.md
- abstract.hbs
- package.json
- tests/.eslintrc.cjs
- tests/10-vcdm2.js
- tests/TestEndpoints.js
- tests/assertions.js
- tests/data-generator.js
- tests/mock.data.js
- tests/receive-json.js
Turns out the W3C does *not* use the `BSD-3-Clause` for test suites. There's a
[dedicated policy for test suites](https://www.w3.org/copyright/test-suites-licenses/).
This policy stipulates the use of a "forked" BSD-style license AND a unique
test suite license which are considered "mutually exclusive" and the selection
of which one applies is left to the _licensee_ (depending on the use case).
This PR makes that change as well as applying the custom license names to all
files (either directly or via the `.reuse/dep5` file) following the
[REUSE v3 specification](https://reuse.software/spec/). This can be tested
using the [reuse tool](https://github.com/fsfe/reuse-tool).
> Properly license.

- tests/input/credential-type-unmapped-fail.json
The `@vocab` catch-all would mean that any compliant processor would
always only ever create URLs...even it invalid. Setting `@vocab` to
`null` should prevent that...which should cause a rejection.
> Prevent `@vocab` catch-all for types as URL test.

- .eslintrc.cjs
- tests/10-vcdm2.js
- Explain why test is skipped.
- Remove skipped test/req no longer in spec.
- Enable createVp in context property test.
- Link to text for section 1.3 Conformance tests.
- Link to text for section 4.3 Identifiers tests.
- Link to text for section 4.3 Types tests.
- Add note about not testing 4.5 name/desc.
- Link to text for section 4.6 Cred Subject tests.
- Link to text for section 4.7 Issuers tests.
- Link to text for section 4.8 Validity Period.
- Link to text for section 4.9 Securing Mechanisms.
- Link to text for section 4.10 Status.
> Adding annotations and did some clean up.

- tests/10-vcdm2.js
It was getting very hard to understand the growing list of MUSTs relative to
the specification. The tests are now grouped into similarly named sections
with links in the code (at least) to those sections.
I plan to do more (likely in the upstream reporter) to make it possible to
link to the sections of the spec and provide basic descriptions of what the
tests are about.
Note: this one stacks on top of #73 which is still being polished.
> Group tests into sections.

- tests/10-vcdm2.js
Once the mocah reporter that supports links is shipped, this will
provide much easier access to everyone looking to relate statements
made in the test suite with claims made in the specification.
> Move link comments to be link data.

- tests/TestEndpoints.js
Partially addresses #83.
Adds a try catch when fetching implementation endpoints.
Add an if condition if no endpoint is set when conducting a test (this is so the test suite doesn't mark it as passed when the call is rejected)
> Fix missing endpoint

- tests/10-vcdm2.js
- tests/input/credential-refresh-type-ok.json
- tests/input/credential-schema-type-ok.json
- Break up objects w/types list into separate tests.
- Add positive `refreshService.type` test.
- Add positive `credentialSchema.type` test.
> Breakup long `type` tests.

- README.md
> docs(fix): fix markdown link format

- tests/10-vcdm2.js
- tests/assertions.js
- tests/data-generator.js
DRY up a pattern used to test if a invalid valid vc is rejected as issuance or verification
Comment said pattern for better understanding.
change magic number for time stamp skew to `oneYear`
p.s. this is a duplicate call on the issuer and verifier so we might consider doing the call once and awaiting the promise twice.
> DRY up tests that should be rejected either as issuance or verification.

- tests/10-vcdm2.js
- tests/input/credential-validfrom-far-future-ok.json
- Add `validFrom` in the far future test.
- Switch back to + based string concat.
- Use more explicit checks on issued VC.
- Await and assert remaining `proof` tests.
> Resolve some more TODOs.

- tests/mock.data.js
Closes #115
- Adds null check to credential issuer before doing `'id' in credential.issuer` check.
> Add issuer null check to mock data request builder

- tests/input/relatedResource/relatedResource-missing-id-fail.json
> Remove `id` from input for "`relatedResource` missing `id`" test

- .gitignore
- README.md
- package.json
This enables local allure report generation for developers.
> Enable allure dev reporting

- README.md
This is to partially address the concerns raised in #127.
It's not a requirement to use data integrity to be conformant with this test suite. This test suite doesn't test the securing mechanism, only the data model.
> Add readme section about the `EnvelopingProof` tag usage.

- tests/1-3-conformance.js
- tests/4-3-contexts.js
- tests/4-4-identifiers.js
- tests/4-5-types.js
- tests/4-6-names-and-descriptions.js
- tests/4-7-issuer.js
- tests/4-8-credential-subject.js
- tests/4-9-validity-period.js
- tests/410-status.js
- tests/411-data-schemas.js
- tests/413-verifiable-presentations.js
- tests/413.2-envelopes.js
- tests/50-advanced-concepts.js
I had occurrences where my server was returning a different type of error than what the test suite was expecting (ex: returning an `HTTPException` instead of an `HTTPError`) and marked the test as failed even if my server behaved correctly. I wonder if checking for a specific type of error is too strict of a validation here?
> Remove strict name validation on assert.rejects statements

- tests/4.09-validity-period.js
This is currently skipped and not testable due to the interpretation happening
within the implementation and not resulting in testable output.
> Remove time value must be UTC test.

- tests/5-advanced-concepts.js
This just fixes the broken highlight link value. @PatStLouis is tackling some spec updates here separately.
> Fix link to digest provided by issuer text.

- tests/5-advanced-concepts.js
The removed text dictates a requirement on future specifications which utilize
VCv2...not on VCv2 itself. So it is not testable with code against an implementation.
> Remove untestable, future-spec requirement.

- tests/input/presentation-context-combo1-ok.json
- tests/input/presentation-context-combo2-ok.json
According to spec https://w3c.github.io/vc-data-model/#presentations-including-holder-claims
VP & VC, which are used for this type of test, are self-asserted and should include holder property. 
Also, there is a test case to validate that holder is required for such types of presentations https://github.com/w3c/vc-data-model-2.0-test-suite/blob/main/tests/4.13-verifiable-presentations.js#L133
> fix: add holder for self-asserted verifiable credential

- tests/4.13.2-envelopes.js
- tests/helpers.js
The helper functions were not throwing error properly for the assertions.
Some of the tests weren't passing the variables properly.
> Fix helper function calls for enveloped tests
